### ISSUE TITLE
go-pardocs plan fails for JWP DR 151018.pdf

### ISSUE THREAD

**Issue by kaerumy** [Sinar/go-pardocs#2]
```GetPlainText ERROR: %!w(string=)```

[JWP DR 151018.pdf](https://github.com/Sinar/go-pardocs/files/3368054/JWP.DR.151018.pdf)

**Comment by leowmjw** [comment]
This is a bug in the underlying library (https://github.com/ledongthuc/pdf
); which does not take filing an issue; will have to fix that library first.

Workaround is to open and re-export back out; it works!

<img width="398" alt="Screen Shot 2019-07-09 at 12 32 46 AM" src="https://user-images.githubusercontent.com/920784/60826995-b8b39080-a1e1-11e9-8731-ba6f26a8fac3.png">

Output of plan on the clean PDF:
```
$ go-pardocs plan -session par1sesi1 -type L ~/Downloads/JWP.DR.151018_clean.pdf 
2019/07/09 00:33:12 Welcome to Sinar Project go-pardocs!
2019/07/09 00:33:12 In plan Execute ..
2019/07/09 00:33:12 AbsoluteSourcePDFPath:  /Users/leow/Downloads/JWP.DR.151018_clean.pdf
2019/07/09 00:33:12 AbsoluteWorkingDir:  /Users/leow/GOMOD/go-pardocs
2019/07/09 00:33:12 In Plan ..
In ExtractPDF ...
...
no code space found
Probably front page; do semthign with this ..
```
<img width="697" alt="Screen Shot 2019-07-09 at 12 34 45 AM" src="https://user-images.githubusercontent.com/920784/60827006-c0733500-a1e1-11e9-82bb-6278c2401f29.png">

**Comment by leowmjw** [comment]
Will need to fork; can try this fork as the base --> https://github.com/dcu/pdf

Can also review the original upstream PR GetPlainText --> https://github.com/rsc/pdf/pull/21

**Comment by leowmjw** [comment]
Caveat is https://github.com/Sinar/go-pardocs/files/3368054/JWP.DR.151018.pdf needs to be named "JWP_DR_151018.pdf" until #6 is fixed
