### ISSUE TITLE
split.yml not created for Bukan Lisan July 2019 session

### ISSUE THREAD

**Issue by kaerumy** [Sinar/go-pardocs#8]
Command run

```
./go-pardocs plan -session par14p2m2 -type BL ./raw/BukanLisan/Jawapan\ Bertulis\ dikemaskini\ pada\ 18\ Sept\ 2019.pdf
```

[debug.txt](https://github.com/Sinar/go-pardocs/files/3722810/debug.txt)

**Comment by leowmjw** [comment]
Latest release v1.0.1 seem to run fine.  

Closing for now (split file attached):

[split.txt](https://github.com/Sinar/go-pardocs/files/4006942/split.txt)
